# compose.yaml

version: '3.8'

services:
  app:
    image: sctcarmelo/projeto_cloud:latest
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME:-projeto}
      - DB_USER=${DB_USER:-projeto}
      - DB_PASSWORD=${DB_PASSWORD:-projeto}
      - SECRET_KEY=${SECRET_KEY:-projeto}
    restart: always
    # volumes:
      # - ./app:/app  # Remover ou comentar esta linha

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=${DB_NAME:-projeto}
      - POSTGRES_USER=${DB_USER:-projeto}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-projeto}

